version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10


    working_directory: ~/kes
    steps:
      - checkout

      - run:
          name: Install
          command: |
            npm install
            PATH=$PATH:/home/circleci/kes/bin

      - run:
          name: Test Examples
          command: |
            mkdir ~/example1
            cp -r examples/lambdas ~/example1/.kes
            cd ~/example1/
            cli.js cf compile
            cli.js cf validate

