version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10


    working_directory: ~/kes
    steps:
      - checkout

      - run:
          name: Install
          command: |
            sudo npm install -g .

      - run:
          name: Test Examples
          command: |
            mkdir ~/example1
            cp -r examples/lambdas ~/example1/.kes
            cd ~/example1/
            kes cf compile
            kes cf validate

      - run:
          name: docs
          command: |
            npm run html-docs
            cd _docs
            git init
            git config user.name "Devseed-CI"
            git config user.email "dev@developmentseed.org"
            git add .
            git commit -m "CI deploy [skip ci]"
            git remote add origin git@github.com:developmentseed/kes.git
            git push origin master:gh-pages --force

      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
              npm publish
            fi

