kesTestDeployment:
  stackName: kes-test-using-template
  noDash: myDeployment
  system_bucket: devseed-kes-deployment 

  buckets:
    internal:
      name: 'something'
    tests: myTestArtifacts
  
  lambdas:
    func3: # function name must match the lambda folder name in build directory
      handler: index.handler
      timeout: 300
      source: 'examples/code/lambda1/'