AWSTemplateFormatVersion: '2010-09-09'
Description: 'stack: kes-nested-example | deployed by Kes'
Parameters:
  Lambda1Arn:
    Type: String
    Description: arn of lambda 1

Resources:

  #################################################
  # SNS config BEGIN
  #################################################
  subscribeToLambda1Sns:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: kes-nested-example-subscribeToLambda1
      Subscription:
        - Endpoint: !Ref Lambda1Arn
          Protocol: lambda

  #################################################
  # SNS config END
  #################################################

  #################################################
  # SQS config BEGIN
  #################################################
  mySqsSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: kes-nested-example-mySqs
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt [mySqsFailedSQS, Arn]
        maxReceiveCount: 20
      VisibilityTimeout: 10

  mySqsFailedSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: kes-nested-example-mySqs-failed

  #################################################
  # SQS config END
  #################################################

Outputs:

  mySqsSQSOutput:
    Value: !Ref mySqsSQS

  subscribeToLambda1SnsArn:
    Value: !Ref subscribeToLambda1Sns
