default:
  stackName: my-kes-project

  lambdas:
    - name: func1 # function name must match the lambda folder name in build directory
      handler: func1.handler
      timeout: 300
      s3Source:
        bucket: mybucket
        key: file.zip
    - name: func2 # function name must match the lambda folder name in build directory
      handler: func2.handler
      timeout: 300
      envs:
        CUSTOM_ENV: myValue
      s3Source:
        bucket: mybucket
        key: file.zip

production:
  stackName: my-kes-project-prod

